import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';


export interface Time {
  codigo: number;
  nome: string;
  anoFundacao: number;
  estadio: string;
  serie: string;
}
let brUm = "Brasileirão Série A";
let brDois = "Brasileirão Série B";
let brTre = "Brasileirão Série C";
let brQuatro = "Brasileirão Série D";

const TIMES_DATA: Time[] = [
  { codigo: 1, nome: 'Flamengo', anoFundacao: 1895, estadio: 'Maracanã', serie: brUm },
  { codigo: 2, nome: 'Grêmio', anoFundacao: 1903, estadio: 'Arena do Grêmio', serie: brUm },
  { codigo: 3, nome: 'Cruzeiro', anoFundacao: 1921, estadio: 'Mineirão', serie: brUm },
  { codigo: 4, nome: 'Atletico MG', anoFundacao: 1908, estadio: 'Arena MRV', serie: brUm },
  { codigo: 5, nome: 'América MG', anoFundacao: 1912, estadio: 'Arena Independência', serie: brDois },
  { codigo: 6, nome: 'Bahia', anoFundacao: 1931, estadio: 'Arena Fonte Nova', serie: brUm },
  { codigo: 7, nome: 'Criciúma', anoFundacao: 1947, estadio: 'Majestoso', serie: brUm },
  { codigo: 8, nome: 'Juventude', anoFundacao: 1913, estadio: 'Estádio Alfredo Jaconi', serie: brUm },
  { codigo: 9, nome: 'Internacional', anoFundacao: 1909, estadio: 'Estádio Beira-Rio', serie: brUm },
  { codigo: 10, nome: 'Corinthians', anoFundacao: 1910, estadio: 'Neo Química Arena', serie: brUm },
  { codigo: 11, nome: 'Palmeiras', anoFundacao: 1914 , estadio: 'Allianz Parque', serie: brUm },
  { codigo: 12, nome: 'São Paulo', anoFundacao: 1930 , estadio: 'Morumbi', serie: brUm },
  { codigo: 13, nome: 'Bragantino', anoFundacao: 1928 , estadio: 'Estádio Nabi Abi Chedid', serie: brUm },
  { codigo: 14, nome: 'Santos', anoFundacao: 1912 , estadio: 'Vila Belmiro', serie: brDois },
  { codigo: 15, nome: 'Grêmio Novorizontino', anoFundacao: 2010 , estadio: 'Jorge Ismael de Biasi', serie: brDois },
  { codigo: 16, nome: 'Mirassol', anoFundacao: 1925, estadio: 'José Maria de Campos Maia', serie: brDois },
  { codigo: 17, nome: 'Atlético GO', anoFundacao: 1937, estadio: 'Estádio Antonio Accioly', serie: brUm },
  { codigo: 18, nome: 'Cuiabá', anoFundacao: 2001, estadio: 'Arena Pantanal', serie: brUm },
  { codigo: 19, nome: 'Fluminense', anoFundacao: 1902, estadio: 'Maracanã', serie: brUm },
  { codigo: 20, nome: 'Vitória', anoFundacao: 1899, estadio: 'Barradão', serie: brUm },
  { codigo: 21, nome: 'Vasco da Gama', anoFundacao: 1898, estadio: 'Estádio São Januário', serie: brUm },
  { codigo: 22, nome: 'Fortaleza', anoFundacao: 1918, estadio: 'Arena Castelão', serie: brUm },
  { codigo: 23, nome: 'Botafogo', anoFundacao: 1904, estadio: 'Estádio Olímpico Nilton Santos', serie: brUm },
  { codigo: 24, nome: 'Athletico', anoFundacao: 1924, estadio: 'Ligga Arena', serie: brUm },
  { codigo: 25, nome: 'Sport', anoFundacao: 1905, estadio: 'Ilha do Retiro', serie: brDois },
  { codigo: 26, nome: 'Vila Nova GO', anoFundacao: 1943, estadio: 'Estádio Serra Dourada', serie: brDois },
  { codigo: 27, nome: 'Ceará', anoFundacao: 1914, estadio: 'Arena Castelão', serie: brDois },
  { codigo: 28, nome: 'Coritiba', anoFundacao: 1909, estadio: 'Estádio Major Couto Pereira', serie: brDois },
  { codigo: 29, nome: 'Avaí', anoFundacao: 1923, estadio: 'Ressacada', serie: brDois },
  { codigo: 30, nome: 'Operário Ferroviário', anoFundacao: 1912, estadio: 'Estádio Germano Krüger', serie: brDois },
  { codigo: 31, nome: 'Amazonas ', anoFundacao: 2019, estadio: 'Arena da Amazônia', serie: brDois },
  { codigo: 32, nome: 'Goiás', anoFundacao: 1943, estadio: 'Estádio Serra Dourada', serie: brDois },
  { codigo: 34, nome: 'Chapecoense', anoFundacao: 1973, estadio: 'Arena Condá', serie: brDois },
  { codigo: 35, nome: 'Botafogo SP', anoFundacao: 1918, estadio: 'Estádio Santa Cruz', serie: brDois },
  { codigo: 36, nome: 'Paysandu', anoFundacao: 1914, estadio: 'Mangueirão', serie: brDois },
  { codigo: 37, nome: 'Brusque', anoFundacao: 1987, estadio: 'Estádio Augusto Bauer', serie: brDois },
  { codigo: 38, nome: 'Ituano', anoFundacao: 1947, estadio: 'Estádio Dr. Novelli Júnior', serie: brDois },
  { codigo: 39, nome: 'CRB', anoFundacao: 1912, estadio: 'Estádio Rei Pelé', serie: brDois },
  { codigo: 40, nome: 'Guarani', anoFundacao: 1911, estadio: ' Estádio Brinco de Ouro da Princesa', serie: brDois },
  { codigo: 41, nome: 'São Bento', anoFundacao: 1913, estadio: 'Estádio Walter Ribeiro', serie: brTre },
  { codigo: 42, nome: 'Botafogo PB', anoFundacao: 1931, estadio: 'Almeidão', serie: brTre },
  { codigo: 43, nome: 'Figueirense', anoFundacao: 1921, estadio: 'Orlando Scarpelli', serie: brTre },
  { codigo: 44, nome: 'Paysandu', anoFundacao: 1914, estadio: 'Mangueirão', serie: brTre },
  { codigo: 45, nome: 'ABC', anoFundacao: 1915, estadio: 'Frasqueirão', serie: brTre },
  { codigo: 46, nome: 'Confiança', anoFundacao: 1936, estadio: 'Batistão', serie: brTre },
  { codigo: 47, nome: 'São José RS', anoFundacao: 1913, estadio: 'Passo d’Areia', serie: brTre },
  { codigo: 48, nome: 'Remo', anoFundacao: 1905, estadio: 'Mangueirão', serie: brTre },
  { codigo: 49, nome: 'Volta Redonda', anoFundacao: 1976, estadio: 'Raulino de Oliveira', serie: brTre },
  { codigo: 50, nome: 'Ypiranga RS', anoFundacao: 1924, estadio: 'Colosso da Lagoa', serie: brTre },
  { codigo: 51, nome: 'Altos', anoFundacao: 2013, estadio: 'Felipão', serie: brTre },
  { codigo: 52, nome: 'Ferroviário', anoFundacao: 1933, estadio: 'Presidente Vargas', serie: brTre },
  { codigo: 53, nome: 'Manaus FC', anoFundacao: 2013, estadio: 'Arena da Amazônia', serie: brTre },
  { codigo: 54, nome: 'Aparecidense', anoFundacao: 1985, estadio: 'Aníbal Toledo', serie: brTre },
  { codigo: 55, nome: 'Vitória ES', anoFundacao: 1912, estadio: 'Salvador Venâncio da Costa', serie: brQuatro },
  { codigo: 56, nome: 'Portuguesa RJ', anoFundacao: 1924, estadio: 'Luso-Brasileiro', serie: brQuatro },
  { codigo: 57, nome: 'Caxias', anoFundacao: 1935, estadio: 'Centenário', serie: brQuatro },
  { codigo: 58, nome: 'Uberlândia', anoFundacao: 1922, estadio: 'Parque do Sabiá', serie: brQuatro },
  { codigo: 59, nome: 'Brusque', anoFundacao: 1987, estadio: 'Augusto Bauer', serie: brQuatro },
  { codigo: 60, nome: 'Brasil de Pelotas', anoFundacao: 1911, estadio: 'Bento Freitas', serie: brQuatro },
  { codigo: 61, nome: 'Campinense', anoFundacao: 1915, estadio: 'O Amigão', serie: brQuatro },
  { codigo: 62, nome: 'Jacuipense', anoFundacao: 1965, estadio: 'Eliel Martins', serie: brQuatro },
  { codigo: 63, nome: 'Floresta', anoFundacao: 1954, estadio: 'Domingão', serie: brQuatro },
  { codigo: 64, nome: 'Imperatriz', anoFundacao: 1962, estadio: 'Frei Epifânio', serie: brQuatro },
  { codigo: 65, nome: 'Santa Cruz', anoFundacao: 1914, estadio: 'Arruda', serie: brQuatro },
  { codigo: 66, nome: 'Moto Club', anoFundacao: 1937, estadio: 'Castelão', serie: brQuatro },
  { codigo: 67, nome: 'América RN', anoFundacao: 1915, estadio: 'Arena das Dunas', serie: brQuatro },
  { codigo: 68, nome: 'Juazeirense', anoFundacao: 2006, estadio: 'Adauto Moraes', serie: brQuatro },
  { codigo: 69, nome: 'ASA', anoFundacao: 1952, estadio: 'Coaracy da Mata Fonseca', serie: brQuatro },
  { codigo: 70, nome: 'Sergipe', anoFundacao: 1909, estadio: 'Batistão', serie: brQuatro },
  { codigo: 71, nome: 'Icasa', anoFundacao: 1963, estadio: 'Romeirão', serie: brQuatro },
  { codigo: 72, nome: 'XV de Piracicaba', anoFundacao: 1913, estadio: 'Barão de Serra Negra', serie: brQuatro },
  { codigo: 73, nome: 'Anapolina', anoFundacao: 1948, estadio: 'Jonas Duarte', serie: brQuatro },
  { codigo: 74, nome: 'Atlético Acreano', anoFundacao: 1952, estadio: 'Arena da Floresta', serie: brQuatro },
  { codigo: 75, nome: 'Fast Clube', anoFundacao: 1930, estadio: 'Arena da Amazônia', serie: brQuatro },
  { codigo: 76, nome: 'Sampaio Corrêa', anoFundacao: 1923, estadio: 'Castelão', serie: brQuatro },
  { codigo: 77, nome: 'Paragominas', anoFundacao: 2012, estadio: 'Arena Verde', serie: brQuatro },
  { codigo: 78, nome: 'Marcílio Dias', anoFundacao: 1919, estadio: 'Dr. Hercílio Luz', serie: brQuatro },
  { codigo: 79, nome: 'Treze', anoFundacao: 1925, estadio: 'Presidente Vargas', serie: brQuatro },
  { codigo: 80, nome: 'Tocantinópolis', anoFundacao: 1989, estadio: 'Ribeirão', serie: brQuatro },
  { codigo: 81, nome: 'Barcelona', anoFundacao: 1899, estadio: 'Camp Nou', serie: 'La Liga' },
  { codigo: 82, nome: 'Real Madrid', anoFundacao: 1902, estadio: 'Santiago Bernabéu', serie: 'La Liga' },
  { codigo: 83, nome: 'Manchester United', anoFundacao: 1878, estadio: 'Old Trafford', serie: 'Premier League' },
  { codigo: 84, nome: 'Liverpool', anoFundacao: 1892, estadio: 'Anfield', serie: 'Premier League' },
  { codigo: 85, nome: 'Bayern Munich', anoFundacao: 1900, estadio: 'Allianz Arena', serie: 'Bundesliga' },
  { codigo: 86, nome: 'Borussia Dortmund', anoFundacao: 1909, estadio: 'Signal Iduna Park', serie: 'Bundesliga' },
  { codigo: 87, nome: 'Paris Saint-Germain', anoFundacao: 1970, estadio: 'Parc des Princes', serie: 'Ligue 1' },
  { codigo: 88, nome: 'Olympique de Marseille', anoFundacao: 1899, estadio: 'Stade Vélodrome', serie: 'Ligue 1' },
  { codigo: 89, nome: 'Juventus', anoFundacao: 1897, estadio: 'Allianz Stadium', serie: 'Serie A' },
  { codigo: 90, nome: 'AC Milan', anoFundacao: 1899, estadio: 'San Siro', serie: 'Serie A' },
  { codigo: 91, nome: 'Inter de Milão', anoFundacao: 1908, estadio: 'San Siro', serie: 'Serie A' },
  { codigo: 92, nome: 'Roma', anoFundacao: 1927, estadio: 'Stadio Olimpico', serie: 'Serie A' },
  { codigo: 93, nome: 'Ajax', anoFundacao: 1900, estadio: 'Johan Cruyff Arena', serie: 'Eredivisie' },
  { codigo: 94, nome: 'PSV Eindhoven', anoFundacao: 1913, estadio: 'Philips Stadion', serie: 'Eredivisie' },
  { codigo: 95, nome: 'Feyenoord', anoFundacao: 1908, estadio: 'De Kuip', serie: 'Eredivisie' },
  { codigo: 96, nome: 'Porto', anoFundacao: 1893, estadio: 'Estádio do Dragão', serie: 'Primeira Liga' },
  { codigo: 97, nome: 'Benfica', anoFundacao: 1904, estadio: 'Estádio da Luz', serie: 'Primeira Liga' },
  { codigo: 98, nome: 'Sporting', anoFundacao: 1906, estadio: 'Estádio José Alvalade', serie: 'Primeira Liga' },
  { codigo: 99, nome: 'Celtic', anoFundacao: 1887, estadio: 'Celtic Park', serie: 'Scottish Premiership' },
  { codigo: 100, nome: 'Rangers', anoFundacao: 1872, estadio: 'Ibrox Stadium', serie: 'Scottish Premiership' },
  { codigo: 101, nome: 'Galatasaray', anoFundacao: 1905, estadio: 'Nef Stadium', serie: 'Super Lig' },
  { codigo: 102, nome: 'Fenerbahçe', anoFundacao: 1907, estadio: 'Şükrü Saracoğlu Stadium', serie: 'Super Lig' },
  { codigo: 103, nome: 'Besiktas', anoFundacao: 1903, estadio: 'Vodafone Park', serie: 'Super Lig' },
  { codigo: 104, nome: 'Zenit', anoFundacao: 1925, estadio: 'Gazprom Arena', serie: 'Russian Premier League' },
  { codigo: 105, nome: 'Spartak Moscow', anoFundacao: 1922, estadio: 'Otkritie Arena', serie: 'Russian Premier League' },
  { codigo: 106, nome: 'Shakhtar Donetsk', anoFundacao: 1936, estadio: 'Donbass Arena', serie: 'Ukrainian Premier League' },
  { codigo: 107, nome: 'Dynamo Kyiv', anoFundacao: 1927, estadio: 'NSC Olimpiyskiy', serie: 'Ukrainian Premier League' },
  { codigo: 108, nome: 'Boca Juniors', anoFundacao: 1905, estadio: 'La Bombonera', serie: 'Liga Profesional' },
  { codigo: 109, nome: 'River Plate', anoFundacao: 1901, estadio: 'Monumental', serie: 'Liga Profesional' },
  { codigo: 110, nome: 'Independiente', anoFundacao: 1905, estadio: 'Estadio Libertadores de América', serie: 'Liga Profesional' },
  { codigo: 111, nome: 'Racing Club', anoFundacao: 1903, estadio: 'Estadio Presidente Perón', serie: 'Liga Profesional' },
  { codigo: 112, nome: 'Peñarol', anoFundacao: 1891, estadio: 'Estadio Campeón del Siglo', serie: 'Primera División' },
  { codigo: 113, nome: 'Nacional', anoFundacao: 1899, estadio: 'Gran Parque Central', serie: 'Primera División' },
  { codigo: 114, nome: 'Colo-Colo', anoFundacao: 1925, estadio: 'Monumental David Arellano', serie: 'Primera División' },
  { codigo: 115, nome: 'Universidad de Chile', anoFundacao: 1927, estadio: 'Estadio Nacional', serie: 'Primera División' },
  { codigo: 116, nome: 'LA Galaxy', anoFundacao: 1994, estadio: 'Dignity Health Sports Park', serie: 'MLS' },
  { codigo: 117, nome: 'New York City FC', anoFundacao: 2013, estadio: 'Yankee Stadium', serie: 'MLS' },
  { codigo: 118, nome: 'Toronto FC', anoFundacao: 2006, estadio: 'BMO Field', serie: 'MLS' },
  { codigo: 119, nome: 'Club América', anoFundacao: 1916, estadio: 'Estadio Azteca', serie: 'Liga MX' },
  { codigo: 120, nome: 'Chivas Guadalajara', anoFundacao: 1906, estadio: 'Estadio Akron', serie: 'Liga MX' },
  { codigo: 121, nome: 'Real Betis', anoFundacao: 1907, estadio: 'Estadio Benito Villamarín', serie: 'La Liga' },
  { codigo: 122, nome: 'Athletic Bilbao', anoFundacao: 1898, estadio: 'San Mamés', serie: 'La Liga' },
  { codigo: 123, nome: 'Real Sociedad', anoFundacao: 1909, estadio: 'Reale Arena', serie: 'La Liga' },
  { codigo: 124, nome: 'Celta de Vigo', anoFundacao: 1923, estadio: 'Estadio Municipal de Balaídos', serie: 'La Liga' },
  { codigo: 125, nome: 'Osasuna', anoFundacao: 1920, estadio: 'Estadio El Sadar', serie: 'La Liga' },
  { codigo: 126, nome: 'Valencia', anoFundacao: 1919, estadio: 'Estadio de Mestalla', serie: 'La Liga' },
  { codigo: 127, nome: 'Espanyol', anoFundacao: 1900, estadio: 'RCDE Stadium', serie: 'La Liga' },
  { codigo: 128, nome: 'Villarreal', anoFundacao: 1923, estadio: 'Estadio de la Cerámica', serie: 'La Liga' },
  { codigo: 129, nome: 'Getafe', anoFundacao: 1983, estadio: 'Coliseum Alfonso Pérez', serie: 'La Liga' },
  { codigo: 130, nome: 'Granada', anoFundacao: 1931, estadio: 'Estadio Nuevo Los Cármenes', serie: 'La Liga' },
  { codigo: 131, nome: 'Alavés', anoFundacao: 1921, estadio: 'Estadio Mendizorrotza', serie: 'La Liga' },
  { codigo: 132, nome: 'Rayo Vallecano', anoFundacao: 1924, estadio: 'Estadio de Vallecas', serie: 'La Liga' },
  { codigo: 133, nome: 'Mallorca', anoFundacao: 1916, estadio: 'Estadio de Son Moix', serie: 'La Liga' },
  { codigo: 134, nome: 'Almería', anoFundacao: 1989, estadio: 'Estadio de los Juegos Mediterráneos', serie: 'La Liga' },
  { codigo: 135, nome: 'Levante', anoFundacao: 1909, estadio: 'Estadi Ciutat de València', serie: 'La Liga' },
  { codigo: 136, nome: 'Leganés', anoFundacao: 1928, estadio: 'Estadio Municipal Butarque', serie: 'La Liga' },
  { codigo: 137, nome: 'S.D. Eibar', anoFundacao: 1940, estadio: 'Ipurua Municipal Stadium', serie: 'La Liga' },
  { codigo: 138, nome: 'Cádiz', anoFundacao: 1910, estadio: 'Estadio Nuevo Mirandilla', serie: 'La Liga' },
  { codigo: 139, nome: 'Elche', anoFundacao: 1923, estadio: 'Estadio Manuel Martínez Valero', serie: 'La Liga' },
  { codigo: 140, nome: 'Real Valladolid', anoFundacao: 1928, estadio: 'Estadio José Zorrilla', serie: 'La Liga' },
  { codigo: 141, nome: 'West Ham', anoFundacao: 1895, estadio: 'London Stadium', serie: 'Premier League' },
  { codigo: 142, nome: 'Everton', anoFundacao: 1878, estadio: 'Goodison Park', serie: 'Premier League' },
  { codigo: 143, nome: 'Leicester City', anoFundacao: 1884, estadio: 'King Power Stadium', serie: 'Premier League' },
  { codigo: 144, nome: 'Aston Villa', anoFundacao: 1874, estadio: 'Villa Park', serie: 'Premier League' },
  { codigo: 145, nome: 'Wolverhampton', anoFundacao: 1877, estadio: 'Molineux Stadium', serie: 'Premier League' },
  { codigo: 146, nome: 'Bournemouth', anoFundacao: 1890, estadio: 'Vitality Stadium', serie: 'Premier League' },
  { codigo: 147, nome: 'Brentford', anoFundacao: 1889, estadio: 'Brentford Community Stadium', serie: 'Premier League' },
  { codigo: 148, nome: 'Fulham', anoFundacao: 1879, estadio: 'Craven Cottage', serie: 'Premier League' },
  { codigo: 149, nome: 'Newcastle United', anoFundacao: 1892, estadio: 'St. James Park', serie: 'Premier League' },
  { codigo: 150, nome: 'Manchester City', anoFundacao: 1880, estadio: 'Etihad Stadium', serie: 'Premier League' },
  { codigo: 151, nome: 'Tottenham Hotspur', anoFundacao: 1882, estadio: 'Tottenham Hotspur Stadium', serie: 'Premier League' },
  { codigo: 152, nome: 'Chelsea', anoFundacao: 1905, estadio: 'Stamford Bridge', serie: 'Premier League' },
  { codigo: 153, nome: 'Arsenal', anoFundacao: 1886, estadio: 'Emirates Stadium', serie: 'Premier League' },
  { codigo: 154, nome: 'Manchester United', anoFundacao: 1878, estadio: 'Old Trafford', serie: 'Premier League' },
  { codigo: 155, nome: 'Cardiff City', anoFundacao: 1899, estadio: 'Cardiff City Stadium', serie: 'EFL Championship' },
  { codigo: 156, nome: 'Swansea City', anoFundacao: 1912, estadio: 'Swansea.com Stadium', serie: 'EFL Championship' },
  { codigo: 157, nome: 'Birmingham City', anoFundacao: 1875, estadio: 'St. Andrews', serie: 'EFL Championship' },
  { codigo: 158, nome: 'Huddersfield Town', anoFundacao: 1908, estadio: 'John Smiths Stadium', serie: 'EFL Championship' },
  { codigo: 159, nome: 'Queens Park Rangers', anoFundacao: 1882, estadio: 'Loftus Road', serie: 'EFL Championship' },
  { codigo: 160, nome: 'Middlesbrough', anoFundacao: 1876, estadio: 'Riverside Stadium', serie: 'EFL Championship' },
  { codigo: 161, nome: 'Nottingham Forest', anoFundacao: 1865, estadio: 'City Ground', serie: 'EFL Championship' },
  { codigo: 162, nome: 'Sheffield United', anoFundacao: 1889, estadio: 'Bramall Lane', serie: 'EFL Championship' },
  { codigo: 163, nome: 'Burnley', anoFundacao: 1882, estadio: 'Turf Moor', serie: 'EFL Championship' },
  { codigo: 164, nome: 'Luton Town', anoFundacao: 1885, estadio: 'Kenilworth Road', serie: 'EFL Championship' },
  { codigo: 165, nome: 'Blackburn Rovers', anoFundacao: 1875, estadio: 'Ewood Park', serie: 'EFL Championship' },
  { codigo: 166, nome: 'Bristol City', anoFundacao: 1894, estadio: 'Ashton Gate', serie: 'EFL Championship' },
  { codigo: 167, nome: 'Stoke City', anoFundacao: 1863, estadio: 'Bet365 Stadium', serie: 'EFL Championship' },
  { codigo: 168, nome: 'Wigan Athletic', anoFundacao: 1932, estadio: 'DW Stadium', serie: 'EFL Championship' },
  { codigo: 169, nome: 'Barnsley', anoFundacao: 1887, estadio: 'Oakwell', serie: 'EFL Championship' },
  { codigo: 170, nome: 'Peterborough United', anoFundacao: 1934, estadio: 'London Road Stadium', serie: 'EFL Championship' },
  { codigo: 171, nome: 'Southampton', anoFundacao: 1885, estadio: 'St. Marys Stadium', serie: 'EFL Championship' },
  { codigo: 172, nome: 'Bournemouth', anoFundacao: 1890, estadio: 'Vitality Stadium', serie: 'EFL Championship' },
  { codigo: 173, nome: 'Luton Town', anoFundacao: 1885, estadio: 'Kenilworth Road', serie: 'EFL Championship' },
  { codigo: 174, nome: 'Sheffield Wednesday', anoFundacao: 1867, estadio: 'Hillsborough Stadium', serie: 'EFL Championship' },
  { codigo: 175, nome: 'Colchester United', anoFundacao: 1937, estadio: 'JobServe Community Stadium', serie: 'EFL League Two' },
  { codigo: 176, nome: 'Northampton Town', anoFundacao: 1897, estadio: 'Sixfields Stadium', serie: 'EFL League Two' },
  { codigo: 177, nome: 'Newport County', anoFundacao: 1912, estadio: 'Rodney Parade', serie: 'EFL League Two' },
  { codigo: 178, nome: 'Portsmouth', anoFundacao: 1898, estadio: 'Fratton Park', serie: 'EFL League One' },
  { codigo: 179, nome: 'Oxford United', anoFundacao: 1893, estadio: 'Kassam Stadium', serie: 'EFL League One' },
  { codigo: 180, nome: 'Sunderland', anoFundacao: 1879, estadio: 'Stadium of Light', serie: 'EFL League One' },
  { codigo: 181, nome: 'Wimbledon', anoFundacao: 2002, estadio: 'Plough Lane', serie: 'EFL League Two' },
  { codigo: 182, nome: 'Bradford City', anoFundacao: 1903, estadio: 'Valley Parade', serie: 'EFL League Two' },
  { codigo: 183, nome: 'Bury', anoFundacao: 1885, estadio: 'Gigg Lane', serie: 'EFL League Two' },
  { codigo: 184, nome: 'Cheltenham Town', anoFundacao: 1887, estadio: 'Whaddon Road', serie: 'EFL League Two' },
  { codigo: 185, nome: 'Morecambe', anoFundacao: 1920, estadio: 'Mazuma Stadium', serie: 'EFL League One' },
  { codigo: 186, nome: 'Accrington Stanley', anoFundacao: 1968, estadio: 'Wham Stadium', serie: 'EFL League One' },
  { codigo: 187, nome: 'Crawley Town', anoFundacao: 1896, estadio: 'Broadfield Stadium', serie: 'EFL League Two' },
  { codigo: 188, nome: 'Hartlepool United', anoFundacao: 1908, estadio: 'Victoria Park', serie: 'EFL League Two' },
  { codigo: 189, nome: 'Salford City', anoFundacao: 1940, estadio: 'Moorside Road', serie: 'EFL League Two' },
  { codigo: 190, nome: 'Stevenage', anoFundacao: 1976, estadio: 'Lamex Stadium', serie: 'EFL League Two' },
  { codigo: 191, nome: 'Doncaster Rovers', anoFundacao: 1879, estadio: 'Eco-Power Stadium', serie: 'EFL League Two' },
  { codigo: 192, nome: 'Leyton Orient', anoFundacao: 1881, estadio: 'Brisbane Road', serie: 'EFL League Two' },
  { codigo: 193, nome: 'Eastleigh', anoFundacao: 1946, estadio: 'Silverlake Stadium', serie: 'National League' },
  { codigo: 194, nome: 'Wrexham', anoFundacao: 1864, estadio: 'Racecourse Ground', serie: 'National League' },
  { codigo: 195, nome: 'Stockport County', anoFundacao: 1883, estadio: 'Edgeley Park', serie: 'National League' },
  { codigo: 196, nome: 'Grimsby Town', anoFundacao: 1878, estadio: 'Blundell Park', serie: 'National League' },
  { codigo: 197, nome: 'Chesterfield', anoFundacao: 1867, estadio: 'Technique Stadium', serie: 'National League' },
  { codigo: 198, nome: 'Dagenham & Redbridge', anoFundacao: 1992, estadio: 'Victoria Road', serie: 'National League' },
  { codigo: 199, nome: 'Halifax Town', anoFundacao: 2008, estadio: 'The Shay', serie: 'National League' },
  { codigo: 200, nome: 'Torquay United', anoFundacao: 1899, estadio: 'Plainmoor', serie: 'National League' },
];

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss']
})
export class TableComponent implements AfterViewInit {
  displayedColumns: string[] = ['codigo', 'nome', 'anoFundacao', 'estadio', 'serie'];
  dataSource = new MatTableDataSource(TIMES_DATA);

  @ViewChild(MatSort) sort!: MatSort;
  @ViewChild(MatPaginator) paginator!: MatPaginator;

  ngAfterViewInit(): void {
    this.dataSource.sort = this.sort;
    this.dataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();

    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }
}
