import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';

export interface Time {
  codigo: number;
  nome: string;
  anoFundacao: number;
  estadio: string;
  serie: string;
}
let brUm = "Brasileirão Série A";
let brDois = "Brasileirão Série B";
let brTre = "Brasileirão Série C";
let brQuatro = "Brasileirão Série D";

const TIMES_DATA: Time[] = [
  { codigo: 1, nome: 'Flamengo', anoFundacao: 1895, estadio: 'Maracanã', serie: brUm },
  { codigo: 2, nome: 'Grêmio', anoFundacao: 1903, estadio: 'Arena do Grêmio', serie: brUm },
  { codigo: 3, nome: 'Cruzeiro', anoFundacao: 1921, estadio: 'Mineirão', serie: brUm },
  { codigo: 4, nome: 'Atletico MG', anoFundacao: 1908, estadio: 'Arena MRV', serie: brUm },
  { codigo: 5, nome: 'América MG', anoFundacao: 1912, estadio: 'Arena Independência', serie: brDois },
  { codigo: 6, nome: 'Bahia', anoFundacao: 1931, estadio: 'Arena Fonte Nova', serie: brUm },
  { codigo: 7, nome: 'Criciúma', anoFundacao: 1947, estadio: 'Majestoso', serie: brUm },
  { codigo: 8, nome: 'Juventude', anoFundacao: 1913, estadio: 'Estádio Alfredo Jaconi', serie: brUm },
  { codigo: 9, nome: 'Internacional', anoFundacao: 1909, estadio: 'Estádio Beira-Rio', serie: brUm },
  { codigo: 10, nome: 'Corinthians', anoFundacao: 1910, estadio: 'Neo Química Arena', serie: brUm },
  { codigo: 11, nome: 'Palmeiras', anoFundacao: 1914 , estadio: 'Allianz Parque', serie: brUm },
  { codigo: 12, nome: 'São Paulo', anoFundacao: 1930 , estadio: 'Morumbi', serie: brUm },
  { codigo: 13, nome: 'Bragantino', anoFundacao: 1928 , estadio: 'Estádio Nabi Abi Chedid', serie: brUm },
  { codigo: 14, nome: 'Santos', anoFundacao: 1912 , estadio: 'Vila Belmiro', serie: brDois },
  { codigo: 15, nome: 'Grêmio Novorizontino', anoFundacao: 2010 , estadio: 'Jorge Ismael de Biasi', serie: brDois },
  { codigo: 16, nome: 'Mirassol', anoFundacao: 1925, estadio: 'José Maria de Campos Maia', serie: brDois },
  { codigo: 17, nome: 'Atlético GO', anoFundacao: 1937, estadio: 'Estádio Antonio Accioly', serie: brUm },
  { codigo: 18, nome: 'Cuiabá', anoFundacao: 2001, estadio: 'Arena Pantanal', serie: brUm },
  { codigo: 19, nome: 'Fluminense', anoFundacao: 1902, estadio: 'Maracanã', serie: brUm },
  { codigo: 20, nome: 'Vitória', anoFundacao: 1899, estadio: 'Barradão', serie: brUm },
  { codigo: 21, nome: 'Vasco da Gama', anoFundacao: 1898, estadio: 'Estádio São Januário', serie: brUm },
  { codigo: 22, nome: 'Fortaleza', anoFundacao: 1918, estadio: 'Arena Castelão', serie: brUm },
  { codigo: 23, nome: 'Botafogo', anoFundacao: 1904, estadio: 'Estádio Olímpico Nilton Santos', serie: brUm },
  { codigo: 24, nome: 'Athletico', anoFundacao: 1924, estadio: 'Ligga Arena', serie: brUm },
  { codigo: 25, nome: 'Sport', anoFundacao: 1905, estadio: 'Ilha do Retiro', serie: brDois },
  { codigo: 26, nome: 'Vila Nova GO', anoFundacao: 1943, estadio: 'Estádio Serra Dourada', serie: brDois },
  { codigo: 27, nome: 'Ceará', anoFundacao: 1914, estadio: 'Arena Castelão', serie: brDois },
  { codigo: 28, nome: 'Coritiba', anoFundacao: 1909, estadio: 'Estádio Major Couto Pereira', serie: brDois },
  { codigo: 29, nome: 'Avaí', anoFundacao: 1923, estadio: 'Ressacada', serie: brDois },
  { codigo: 30, nome: 'Operário Ferroviário', anoFundacao: 1912, estadio: 'Estádio Germano Krüger', serie: brDois },
  { codigo: 31, nome: 'Amazonas ', anoFundacao: 2019, estadio: 'Arena da Amazônia', serie: brDois },
  { codigo: 32, nome: 'Goiás', anoFundacao: 1943, estadio: 'Estádio Serra Dourada', serie: brDois },
  { codigo: 34, nome: 'Chapecoense', anoFundacao: 1973, estadio: 'Arena Condá', serie: brDois },
  { codigo: 35, nome: 'Botafogo SP', anoFundacao: 1918, estadio: 'Estádio Santa Cruz', serie: brDois },
  { codigo: 36, nome: 'Paysandu', anoFundacao: 1914, estadio: 'Mangueirão', serie: brDois },
  { codigo: 37, nome: 'Brusque', anoFundacao: 1987, estadio: 'Estádio Augusto Bauer', serie: brDois },
  { codigo: 38, nome: 'Ituano', anoFundacao: 1947, estadio: 'Estádio Dr. Novelli Júnior', serie: brDois },
  { codigo: 39, nome: 'CRB', anoFundacao: 1912, estadio: 'Estádio Rei Pelé', serie: brDois },
  { codigo: 40, nome: 'Guarani', anoFundacao: 1911, estadio: ' Estádio Brinco de Ouro da Princesa', serie: brDois },
  { codigo: 41, nome: 'São Bento', anoFundacao: 1913, estadio: 'Estádio Walter Ribeiro', serie: brTre },
  { codigo: 42, nome: 'Botafogo PB', anoFundacao: 1931, estadio: 'Almeidão', serie: brTre },
  { codigo: 43, nome: 'Figueirense', anoFundacao: 1921, estadio: 'Orlando Scarpelli', serie: brTre },
  { codigo: 44, nome: 'Paysandu', anoFundacao: 1914, estadio: 'Mangueirão', serie: brTre },
  { codigo: 45, nome: 'ABC', anoFundacao: 1915, estadio: 'Frasqueirão', serie: brTre },
  { codigo: 46, nome: 'Confiança', anoFundacao: 1936, estadio: 'Batistão', serie: brTre },
  { codigo: 47, nome: 'São José RS', anoFundacao: 1913, estadio: 'Passo d’Areia', serie: brTre },
  { codigo: 48, nome: 'Remo', anoFundacao: 1905, estadio: 'Mangueirão', serie: brTre },
  { codigo: 49, nome: 'Volta Redonda', anoFundacao: 1976, estadio: 'Raulino de Oliveira', serie: brTre },
  { codigo: 50, nome: 'Ypiranga RS', anoFundacao: 1924, estadio: 'Colosso da Lagoa', serie: brTre },
  { codigo: 51, nome: 'Altos', anoFundacao: 2013, estadio: 'Felipão', serie: brTre },
  { codigo: 52, nome: 'Ferroviário', anoFundacao: 1933, estadio: 'Presidente Vargas', serie: brTre },
  { codigo: 53, nome: 'Manaus FC', anoFundacao: 2013, estadio: 'Arena da Amazônia', serie: brTre },
  { codigo: 54, nome: 'Aparecidense', anoFundacao: 1985, estadio: 'Aníbal Toledo', serie: brTre },
  { codigo: 55, nome: 'Vitória ES', anoFundacao: 1912, estadio: 'Salvador Venâncio da Costa', serie: brQuatro },
  { codigo: 56, nome: 'Portuguesa RJ', anoFundacao: 1924, estadio: 'Luso-Brasileiro', serie: brQuatro },
  { codigo: 57, nome: 'Caxias', anoFundacao: 1935, estadio: 'Centenário', serie: brQuatro },
  { codigo: 58, nome: 'Uberlândia', anoFundacao: 1922, estadio: 'Parque do Sabiá', serie: brQuatro },
  { codigo: 59, nome: 'Brusque', anoFundacao: 1987, estadio: 'Augusto Bauer', serie: brQuatro },
  { codigo: 60, nome: 'Brasil de Pelotas', anoFundacao: 1911, estadio: 'Bento Freitas', serie: brQuatro },
  { codigo: 61, nome: 'Campinense', anoFundacao: 1915, estadio: 'O Amigão', serie: brQuatro },
  { codigo: 62, nome: 'Jacuipense', anoFundacao: 1965, estadio: 'Eliel Martins', serie: brQuatro },
  { codigo: 63, nome: 'Floresta', anoFundacao: 1954, estadio: 'Domingão', serie: brQuatro },
  { codigo: 64, nome: 'Imperatriz', anoFundacao: 1962, estadio: 'Frei Epifânio', serie: brQuatro },
  { codigo: 65, nome: 'Santa Cruz', anoFundacao: 1914, estadio: 'Arruda', serie: brQuatro },
  { codigo: 66, nome: 'Moto Club', anoFundacao: 1937, estadio: 'Castelão', serie: brQuatro },
  { codigo: 67, nome: 'América RN', anoFundacao: 1915, estadio: 'Arena das Dunas', serie: brQuatro },
  { codigo: 68, nome: 'Juazeirense', anoFundacao: 2006, estadio: 'Adauto Moraes', serie: brQuatro },
  { codigo: 69, nome: 'ASA', anoFundacao: 1952, estadio: 'Coaracy da Mata Fonseca', serie: brQuatro },
  { codigo: 70, nome: 'Sergipe', anoFundacao: 1909, estadio: 'Batistão', serie: brQuatro },
  { codigo: 71, nome: 'Icasa', anoFundacao: 1963, estadio: 'Romeirão', serie: brQuatro },
  { codigo: 72, nome: 'XV de Piracicaba', anoFundacao: 1913, estadio: 'Barão de Serra Negra', serie: brQuatro },
  { codigo: 73, nome: 'Anapolina', anoFundacao: 1948, estadio: 'Jonas Duarte', serie: brQuatro },
  { codigo: 74, nome: 'Atlético Acreano', anoFundacao: 1952, estadio: 'Arena da Floresta', serie: brQuatro },
  { codigo: 75, nome: 'Fast Clube', anoFundacao: 1930, estadio: 'Arena da Amazônia', serie: brQuatro },
  { codigo: 76, nome: 'Sampaio Corrêa', anoFundacao: 1923, estadio: 'Castelão', serie: brQuatro },
  { codigo: 77, nome: 'Paragominas', anoFundacao: 2012, estadio: 'Arena Verde', serie: brQuatro },
  { codigo: 78, nome: 'Marcílio Dias', anoFundacao: 1919, estadio: 'Dr. Hercílio Luz', serie: brQuatro },
  { codigo: 79, nome: 'Treze', anoFundacao: 1925, estadio: 'Presidente Vargas', serie: brQuatro },
  { codigo: 80, nome: 'Tocantinópolis', anoFundacao: 1989, estadio: 'Ribeirão', serie: brQuatro },
  { codigo: 81, nome: 'Barcelona', anoFundacao: 1899, estadio: 'Camp Nou', serie: 'La Liga' },
  { codigo: 82, nome: 'Real Madrid', anoFundacao: 1902, estadio: 'Santiago Bernabéu', serie: 'La Liga' },
  { codigo: 83, nome: 'Manchester United', anoFundacao: 1878, estadio: 'Old Trafford', serie: 'Premier League' },
  { codigo: 84, nome: 'Liverpool', anoFundacao: 1892, estadio: 'Anfield', serie: 'Premier League' },
  { codigo: 85, nome: 'Bayern Munich', anoFundacao: 1900, estadio: 'Allianz Arena', serie: 'Bundesliga' },
  { codigo: 86, nome: 'Borussia Dortmund', anoFundacao: 1909, estadio: 'Signal Iduna Park', serie: 'Bundesliga' },
  { codigo: 87, nome: 'Paris Saint-Germain', anoFundacao: 1970, estadio: 'Parc des Princes', serie: 'Ligue 1' },
  { codigo: 88, nome: 'Olympique de Marseille', anoFundacao: 1899, estadio: 'Stade Vélodrome', serie: 'Ligue 1' },
  { codigo: 89, nome: 'Juventus', anoFundacao: 1897, estadio: 'Allianz Stadium', serie: 'Serie A' },
  { codigo: 90, nome: 'AC Milan', anoFundacao: 1899, estadio: 'San Siro', serie: 'Serie A' },
  { codigo: 91, nome: 'Inter de Milão', anoFundacao: 1908, estadio: 'San Siro', serie: 'Serie A' },
  { codigo: 92, nome: 'Roma', anoFundacao: 1927, estadio: 'Stadio Olimpico', serie: 'Serie A' },
  { codigo: 93, nome: 'Ajax', anoFundacao: 1900, estadio: 'Johan Cruyff Arena', serie: 'Eredivisie' },
  { codigo: 94, nome: 'PSV Eindhoven', anoFundacao: 1913, estadio: 'Philips Stadion', serie: 'Eredivisie' },
  { codigo: 95, nome: 'Feyenoord', anoFundacao: 1908, estadio: 'De Kuip', serie: 'Eredivisie' },
  { codigo: 96, nome: 'Porto', anoFundacao: 1893, estadio: 'Estádio do Dragão', serie: 'Primeira Liga' },
  { codigo: 97, nome: 'Benfica', anoFundacao: 1904, estadio: 'Estádio da Luz', serie: 'Primeira Liga' },
  { codigo: 98, nome: 'Sporting', anoFundacao: 1906, estadio: 'Estádio José Alvalade', serie: 'Primeira Liga' },
  { codigo: 99, nome: 'Celtic', anoFundacao: 1887, estadio: 'Celtic Park', serie: 'Scottish Premiership' },
  { codigo: 100, nome: 'Rangers', anoFundacao: 1872, estadio: 'Ibrox Stadium', serie: 'Scottish Premiership' },
  { codigo: 101, nome: 'Galatasaray', anoFundacao: 1905, estadio: 'Nef Stadium', serie: 'Super Lig' },
  { codigo: 102, nome: 'Fenerbahçe', anoFundacao: 1907, estadio: 'Şükrü Saracoğlu Stadium', serie: 'Super Lig' },
  { codigo: 103, nome: 'Besiktas', anoFundacao: 1903, estadio: 'Vodafone Park', serie: 'Super Lig' },
  { codigo: 104, nome: 'Zenit', anoFundacao: 1925, estadio: 'Gazprom Arena', serie: 'Russian Premier League' },
  { codigo: 105, nome: 'Spartak Moscow', anoFundacao: 1922, estadio: 'Otkritie Arena', serie: 'Russian Premier League' },
  { codigo: 106, nome: 'Shakhtar Donetsk', anoFundacao: 1936, estadio: 'Donbass Arena', serie: 'Ukrainian Premier League' },
  { codigo: 107, nome: 'Dynamo Kyiv', anoFundacao: 1927, estadio: 'NSC Olimpiyskiy', serie: 'Ukrainian Premier League' },
  { codigo: 108, nome: 'Boca Juniors', anoFundacao: 1905, estadio: 'La Bombonera', serie: 'Liga Profesional' },
  { codigo: 109, nome: 'River Plate', anoFundacao: 1901, estadio: 'Monumental', serie: 'Liga Profesional' },
  { codigo: 110, nome: 'Independiente', anoFundacao: 1905, estadio: 'Estadio Libertadores de América', serie: 'Liga Profesional' },
  { codigo: 111, nome: 'Racing Club', anoFundacao: 1903, estadio: 'Estadio Presidente Perón', serie: 'Liga Profesional' },
  { codigo: 112, nome: 'Peñarol', anoFundacao: 1891, estadio: 'Estadio Campeón del Siglo', serie: 'Primera División' },
  { codigo: 113, nome: 'Nacional', anoFundacao: 1899, estadio: 'Gran Parque Central', serie: 'Primera División' },
  { codigo: 114, nome: 'Colo-Colo', anoFundacao: 1925, estadio: 'Monumental David Arellano', serie: 'Primera División' },
  { codigo: 115, nome: 'Universidad de Chile', anoFundacao: 1927, estadio: 'Estadio Nacional', serie: 'Primera División' },
  { codigo: 116, nome: 'LA Galaxy', anoFundacao: 1994, estadio: 'Dignity Health Sports Park', serie: 'MLS' },
  { codigo: 117, nome: 'New York City FC', anoFundacao: 2013, estadio: 'Yankee Stadium', serie: 'MLS' },
  { codigo: 118, nome: 'Toronto FC', anoFundacao: 2006, estadio: 'BMO Field', serie: 'MLS' },
  { codigo: 119, nome: 'Club América', anoFundacao: 1916, estadio: 'Estadio Azteca', serie: 'Liga MX' },
  { codigo: 120, nome: 'Chivas Guadalajara', anoFundacao: 1906, estadio: 'Estadio Akron', serie: 'Liga MX' },
  { codigo: 121, nome: 'Real Betis', anoFundacao: 1907, estadio: 'Estadio Benito Villamarín', serie: 'La Liga' },
  { codigo: 122, nome: 'Athletic Bilbao', anoFundacao: 1898, estadio: 'San Mamés', serie: 'La Liga' },
  { codigo: 123, nome: 'Real Sociedad', anoFundacao: 1909, estadio: 'Reale Arena', serie: 'La Liga' },
  { codigo: 124, nome: 'Celta de Vigo', anoFundacao: 1923, estadio: 'Estadio Municipal de Balaídos', serie: 'La Liga' },
  { codigo: 125, nome: 'Osasuna', anoFundacao: 1920, estadio: 'Estadio El Sadar', serie: 'La Liga' },
  { codigo: 126, nome: 'Valencia', anoFundacao: 1919, estadio: 'Estadio de Mestalla', serie: 'La Liga' },
  { codigo: 127, nome: 'Espanyol', anoFundacao: 1900, estadio: 'RCDE Stadium', serie: 'La Liga' },
  { codigo: 128, nome: 'Villarreal', anoFundacao: 1923, estadio: 'Estadio de la Cerámica', serie: 'La Liga' },
  { codigo: 129, nome: 'Getafe', anoFundacao: 1983, estadio: 'Coliseum Alfonso Pérez', serie: 'La Liga' },
  { codigo: 130, nome: 'Granada', anoFundacao: 1931, estadio: 'Estadio Nuevo Los Cármenes', serie: 'La Liga' },
  { codigo: 131, nome: 'Alavés', anoFundacao: 1921, estadio: 'Estadio Mendizorrotza', serie: 'La Liga' },
  { codigo: 132, nome: 'Rayo Vallecano', anoFundacao: 1924, estadio: 'Estadio de Vallecas', serie: 'La Liga' },
  { codigo: 133, nome: 'Mallorca', anoFundacao: 1916, estadio: 'Estadio de Son Moix', serie: 'La Liga' },
  { codigo: 134, nome: 'Almería', anoFundacao: 1989, estadio: 'Estadio de los Juegos Mediterráneos', serie: 'La Liga' },
  { codigo: 135, nome: 'Levante', anoFundacao: 1909, estadio: 'Estadi Ciutat de València', serie: 'La Liga' },
  { codigo: 136, nome: 'Leganés', anoFundacao: 1928, estadio: 'Estadio Municipal Butarque', serie: 'La Liga' },
  { codigo: 137, nome: 'S.D. Eibar', anoFundacao: 1940, estadio: 'Ipurua Municipal Stadium', serie: 'La Liga' },
  { codigo: 138, nome: 'Cádiz', anoFundacao: 1910, estadio: 'Estadio Nuevo Mirandilla', serie: 'La Liga' },
  { codigo: 139, nome: 'Elche', anoFundacao: 1923, estadio: 'Estadio Manuel Martínez Valero', serie: 'La Liga' },
  { codigo: 140, nome: 'Real Valladolid', anoFundacao: 1928, estadio: 'Estadio José Zorrilla', serie: 'La Liga' },
  { codigo: 141, nome: 'West Ham', anoFundacao: 1895, estadio: 'London Stadium', serie: 'Premier League' },
  { codigo: 142, nome: 'Everton', anoFundacao: 1878, estadio: 'Goodison Park', serie: 'Premier League' },
  { codigo: 143, nome: 'Leicester City', anoFundacao: 1884, estadio: 'King Power Stadium', serie: 'Premier League' },
  { codigo: 144, nome: 'Aston Villa', anoFundacao: 1874, estadio: 'Villa Park', serie: 'Premier League' },
  { codigo: 145, nome: 'Wolverhampton', anoFundacao: 1877, estadio: 'Molineux Stadium', serie: 'Premier League' },
  { codigo: 146, nome: 'Bournemouth', anoFundacao: 1890, estadio: 'Vitality Stadium', serie: 'Premier League' },
  { codigo: 147, nome: 'Brentford', anoFundacao: 1889, estadio: 'Brentford Community Stadium', serie: 'Premier League' },
  { codigo: 148, nome: 'Fulham', anoFundacao: 1879, estadio: 'Craven Cottage', serie: 'Premier League' },
  { codigo: 149, nome: 'Newcastle United', anoFundacao: 1892, estadio: 'St. James Park', serie: 'Premier League' },
  { codigo: 150, nome: 'Manchester City', anoFundacao: 1880, estadio: 'Etihad Stadium', serie: 'Premier League' },
  { codigo: 151, nome: 'Tottenham Hotspur', anoFundacao: 1882, estadio: 'Tottenham Hotspur Stadium', serie: 'Premier League' },
  { codigo: 152, nome: 'Chelsea', anoFundacao: 1905, estadio: 'Stamford Bridge', serie: 'Premier League' },
  { codigo: 153, nome: 'Arsenal', anoFundacao: 1886, estadio: 'Emirates Stadium', serie: 'Premier League' },
  { codigo: 154, nome: 'Manchester United', anoFundacao: 1878, estadio: 'Old Trafford', serie: 'Premier League' },
  { codigo: 155, nome: 'Cardiff City', anoFundacao: 1899, estadio: 'Cardiff City Stadium', serie: 'EFL Championship' },
  { codigo: 156, nome: 'Swansea City', anoFundacao: 1912, estadio: 'Swansea.com Stadium', serie: 'EFL Championship' },
  { codigo: 157, nome: 'Birmingham City', anoFundacao: 1875, estadio: 'St. Andrews', serie: 'EFL Championship' },
  { codigo: 158, nome: 'Huddersfield Town', anoFundacao: 1908, estadio: 'John Smiths Stadium', serie: 'EFL Championship' },
  { codigo: 159, nome: 'Queens Park Rangers', anoFundacao: 1882, estadio: 'Loftus Road', serie: 'EFL Championship' },
  { codigo: 160, nome: 'Middlesbrough', anoFundacao: 1876, estadio: 'Riverside Stadium', serie: 'EFL Championship' },
  { codigo: 161, nome: 'Nottingham Forest', anoFundacao: 1865, estadio: 'City Ground', serie: 'EFL Championship' },
  { codigo: 162, nome: 'Sheffield United', anoFundacao: 1889, estadio: 'Bramall Lane', serie: 'EFL Championship' },
  { codigo: 163, nome: 'Burnley', anoFundacao: 1882, estadio: 'Turf Moor', serie: 'EFL Championship' },
  { codigo: 164, nome: 'Luton Town', anoFundacao: 1885, estadio: 'Kenilworth Road', serie: 'EFL Championship' },
  { codigo: 165, nome: 'Blackburn Rovers', anoFundacao: 1875, estadio: 'Ewood Park', serie: 'EFL Championship' },
  { codigo: 166, nome: 'Bristol City', anoFundacao: 1894, estadio: 'Ashton Gate', serie: 'EFL Championship' },
  { codigo: 167, nome: 'Stoke City', anoFundacao: 1863, estadio: 'Bet365 Stadium', serie: 'EFL Championship' },
  { codigo: 168, nome: 'Wigan Athletic', anoFundacao: 1932, estadio: 'DW Stadium', serie: 'EFL Championship' },
  { codigo: 169, nome: 'Barnsley', anoFundacao: 1887, estadio: 'Oakwell', serie: 'EFL Championship' },
  { codigo: 170, nome: 'Peterborough United', anoFundacao: 1934, estadio: 'London Road Stadium', serie: 'EFL Championship' },
  { codigo: 171, nome: 'Southampton', anoFundacao: 1885, estadio: 'St. Marys Stadium', serie: 'EFL Championship' },
  { codigo: 172, nome: 'Bournemouth', anoFundacao: 1890, estadio: 'Vitality Stadium', serie: 'EFL Championship' },
  { codigo: 173, nome: 'Luton Town', anoFundacao: 1885, estadio: 'Kenilworth Road', serie: 'EFL Championship' },
  { codigo: 174, nome: 'Sheffield Wednesday', anoFundacao: 1867, estadio: 'Hillsborough Stadium', serie: 'EFL Championship' },
  { codigo: 175, nome: 'Colchester United', anoFundacao: 1937, estadio: 'JobServe Community Stadium', serie: 'EFL League Two' },
  { codigo: 176, nome: 'Northampton Town', anoFundacao: 1897, estadio: 'Sixfields Stadium', serie: 'EFL League Two' },
  { codigo: 177, nome: 'Newport County', anoFundacao: 1912, estadio: 'Rodney Parade', serie: 'EFL League Two' },
  { codigo: 178, nome: 'Portsmouth', anoFundacao: 1898, estadio: 'Fratton Park', serie: 'EFL League One' },
  { codigo: 179, nome: 'Oxford United', anoFundacao: 1893, estadio: 'Kassam Stadium', serie: 'EFL League One' },
  { codigo: 180, nome: 'Sunderland', anoFundacao: 1879, estadio: 'Stadium of Light', serie: 'EFL League One' },
  { codigo: 181, nome: 'Wimbledon', anoFundacao: 2002, estadio: 'Plough Lane', serie: 'EFL League Two' },
  { codigo: 182, nome: 'Bradford City', anoFundacao: 1903, estadio: 'Valley Parade', serie: 'EFL League Two' },
  { codigo: 183, nome: 'Bury', anoFundacao: 1885, estadio: 'Gigg Lane', serie: 'EFL League Two' },
  { codigo: 184, nome: 'Cheltenham Town', anoFundacao: 1887, estadio: 'Whaddon Road', serie: 'EFL League Two' },
  { codigo: 185, nome: 'Morecambe', anoFundacao: 1920, estadio: 'Mazuma Stadium', serie: 'EFL League One' },
  { codigo: 186, nome: 'Accrington Stanley', anoFundacao: 1968, estadio: 'Wham Stadium', serie: 'EFL League One' },
  { codigo: 187, nome: 'Crawley Town', anoFundacao: 1896, estadio: 'Broadfield Stadium', serie: 'EFL League Two' },
  { codigo: 188, nome: 'Hartlepool United', anoFundacao: 1908, estadio: 'Victoria Park', serie: 'EFL League Two' },
  { codigo: 189, nome: 'Salford City', anoFundacao: 1940, estadio: 'Moorside Road', serie: 'EFL League Two' },
  { codigo: 190, nome: 'Stevenage', anoFundacao: 1976, estadio: 'Lamex Stadium', serie: 'EFL League Two' },
  { codigo: 191, nome: 'Doncaster Rovers', anoFundacao: 1879, estadio: 'Eco-Power Stadium', serie: 'EFL League Two' },
  { codigo: 192, nome: 'Leyton Orient', anoFundacao: 1881, estadio: 'Brisbane Road', serie: 'EFL League Two' },
  { codigo: 193, nome: 'Eastleigh', anoFundacao: 1946, estadio: 'Silverlake Stadium', serie: 'National League' },
  { codigo: 194, nome: 'Wrexham', anoFundacao: 1864, estadio: 'Racecourse Ground', serie: 'National League' },
  { codigo: 195, nome: 'Stockport County', anoFundacao: 1883, estadio: 'Edgeley Park', serie: 'National League' },
  { codigo: 196, nome: 'Grimsby Town', anoFundacao: 1878, estadio: 'Blundell Park', serie: 'National League' },
  { codigo: 197, nome: 'Chesterfield', anoFundacao: 1867, estadio: 'Technique Stadium', serie: 'National League' },
  { codigo: 198, nome: 'Dagenham & Redbridge', anoFundacao: 1992, estadio: 'Victoria Road', serie: 'National League' },
  { codigo: 199, nome: 'Halifax Town', anoFundacao: 2008, estadio: 'The Shay', serie: 'National League' },
  { codigo: 200, nome: 'Torquay United', anoFundacao: 1899, estadio: 'Plainmoor', serie: 'National League' },
  { codigo: 201, nome: 'Aldershot Town', anoFundacao: 1992, estadio: 'The EBB Stadium', serie: 'National League' },
  { codigo: 202, nome: 'Solihull Moors', anoFundacao: 2007, estadio: 'Damson Park', serie: 'National League' },
  { codigo: 203, nome: 'Notts County', anoFundacao: 1862, estadio: 'Meadow Lane', serie: 'National League' },
  { codigo: 204, nome: 'Bromley', anoFundacao: 1892, estadio: 'Hayes Lane', serie: 'National League' },
  { codigo: 205, nome: 'Barnet', anoFundacao: 1888, estadio: 'The Hive London', serie: 'National League' },
  { codigo: 206, nome: 'Wealdstone', anoFundacao: 1899, estadio: 'Gspur Stadium', serie: 'National League' },
  { codigo: 207, nome: 'Maidenhead United', anoFundacao: 1870, estadio: 'York Road', serie: 'National League' },
  { codigo: 208, nome: 'York City', anoFundacao: 1922, estadio: 'LNER Community Stadium', serie: 'National League' },
  { codigo: 209, nome: 'Braintree Town', anoFundacao: 1898, estadio: 'Cressing Road', serie: 'National League' },
  { codigo: 210, nome: 'Chorley', anoFundacao: 1883, estadio: 'Victory Park', serie: 'National League' },
  { codigo: 211, nome: 'Curzon Ashton', anoFundacao: 1963, estadio: 'Tameside Stadium', serie: 'National League' },
  { codigo: 212, nome: 'Dover Athletic', anoFundacao: 1983, estadio: 'Crabble Athletic Ground', serie: 'National League' },
  { codigo: 213, nome: 'Ebbsfleet United', anoFundacao: 1946, estadio: 'Stonebridge Road', serie: 'National League' },
  { codigo: 214, nome: 'Farsley Celtic', anoFundacao: 1964, estadio: 'The Citadel', serie: 'National League North' },
  { codigo: 215, nome: 'Gloucester City', anoFundacao: 1883, estadio: 'Whaddon Road', serie: 'National League North' },
  { codigo: 216, nome: 'Hereford', anoFundacao: 1881, estadio: 'Edgar Street', serie: 'National League North' },
  { codigo: 217, nome: 'Kettering Town', anoFundacao: 1872, estadio: 'Latimer Park', serie: 'National League North' },
  { codigo: 218, nome: 'Spennymoor Town', anoFundacao: 2005, estadio: 'The Brewery Field', serie: 'National League North' },
  { codigo: 219, nome: 'Southport', anoFundacao: 1881, estadio: 'Haig Avenue', serie: 'National League North' },
  { codigo: 220, nome: 'Darlington', anoFundacao: 1883, estadio: 'Blackwell Meadows', serie: 'National League North' },
  { codigo: 221, nome: 'York City', anoFundacao: 1922, estadio: 'LNER Community Stadium', serie: 'National League North' },
  { codigo: 222, nome: 'Kidderminster Harriers', anoFundacao: 1881, estadio: 'Aggborough', serie: 'National League North' },
  { codigo: 223, nome: 'Chester', anoFundacao: 2010, estadio: 'Deva Stadium', serie: 'National League North' },
  { codigo: 224, nome: 'Stockport County', anoFundacao: 1883, estadio: 'Edgeley Park', serie: 'National League North' },
  { codigo: 225, nome: 'Colchester United', anoFundacao: 1937, estadio: 'JobServe Community Stadium', serie: 'National League North' },
  { codigo: 226, nome: 'Colchester United', anoFundacao: 1937, estadio: 'JobServe Community Stadium', serie: 'EFL League Two' },
  { codigo: 227, nome: 'Leyton Orient', anoFundacao: 1881, estadio: 'Brisbane Road', serie: 'EFL League Two' },
  { codigo: 228, nome: 'Newport County', anoFundacao: 1912, estadio: 'Rodney Parade', serie: 'EFL League Two' },
  { codigo: 229, nome: 'Oldham Athletic', anoFundacao: 1895, estadio: 'Boundary Park', serie: 'EFL League Two' },
  { codigo: 230, nome: 'Northampton Town', anoFundacao: 1897, estadio: 'Sixfields Stadium', serie: 'EFL League Two' },
  { codigo: 231, nome: 'Port Vale', anoFundacao: 1876, estadio: 'Vale Park', serie: 'EFL League Two' },
  { codigo: 232, nome: 'Sutton United', anoFundacao: 1898, estadio: 'VBS Community Stadium', serie: 'EFL League Two' },
  { codigo: 233, nome: 'Tranmere Rovers', anoFundacao: 1884, estadio: 'Prenton Park', serie: 'EFL League Two' },
  { codigo: 234, nome: 'Stevenage', anoFundacao: 1976, estadio: 'Lamex Stadium', serie: 'EFL League Two' },
  { codigo: 235, nome: 'Walsall', anoFundacao: 1888, estadio: 'Bescot Stadium', serie: 'EFL League Two' },
  { codigo: 236, nome: 'Barrow', anoFundacao: 1901, estadio: 'Holker Street', serie: 'EFL League Two' },
  { codigo: 237, nome: 'Harrogate Town', anoFundacao: 1914, estadio: 'CNG Stadium', serie: 'EFL League Two' },
  { codigo: 238, nome: 'Gillingham', anoFundacao: 1893, estadio: 'Priestfield Stadium', serie: 'EFL League Two' },
  { codigo: 239, nome: 'Carlisle United', anoFundacao: 1904, estadio: 'Brunton Park', serie: 'EFL League Two' },
  { codigo: 240, nome: 'Mansfield Town', anoFundacao: 1897, estadio: 'One Call Stadium', serie: 'EFL League Two' },
  { codigo: 241, nome: 'Scunthorpe United', anoFundacao: 1899, estadio: 'Glanford Park', serie: 'EFL League Two' },
  { codigo: 242, nome: 'Portsmouth', anoFundacao: 1898, estadio: 'Fratton Park', serie: 'EFL League One' },
  { codigo: 243, nome: 'Sheffield Wednesday', anoFundacao: 1867, estadio: 'Hillsborough Stadium', serie: 'EFL Championship' },
  { codigo: 244, nome: 'Sunderland', anoFundacao: 1879, estadio: 'Stadium of Light', serie: 'EFL Championship' },
  { codigo: 245, nome: 'West Bromwich Albion', anoFundacao: 1878, estadio: 'The Hawthorns', serie: 'EFL Championship' },
  { codigo: 246, nome: 'Stoke City', anoFundacao: 1863, estadio: 'Bet365 Stadium', serie: 'EFL Championship' },
  { codigo: 247, nome: 'Birmingham City', anoFundacao: 1875, estadio: 'St. Andrew\'s', serie: 'EFL Championship' },
  { codigo: 248, nome: 'Blackburn Rovers', anoFundacao: 1875, estadio: 'Ewood Park', serie: 'EFL Championship' },
  { codigo: 249, nome: 'Coventry City', anoFundacao: 1883, estadio: 'Coventry Building Society Arena', serie: 'EFL Championship' },
  { codigo: 250, nome: 'Cardiff City', anoFundacao: 1899, estadio: 'Cardiff City Stadium', serie: 'EFL Championship' },
  { codigo: 251, nome: 'Middlesbrough', anoFundacao: 1876, estadio: 'Riverside Stadium', serie: 'EFL Championship' },
  { codigo: 252, nome: 'Luton Town', anoFundacao: 1885, estadio: 'Kenilworth Road', serie: 'EFL Championship' },
  { codigo: 253, nome: 'Queens Park Rangers', anoFundacao: 1882, estadio: 'Loftus Road', serie: 'EFL Championship' },
  { codigo: 254, nome: 'Bristol City', anoFundacao: 1894, estadio: 'Ashton Gate', serie: 'EFL Championship' },
  { codigo: 255, nome: 'Blackpool', anoFundacao: 1887, estadio: 'Bloomfield Road', serie: 'EFL Championship' },
  { codigo: 256, nome: 'Rotherham United', anoFundacao: 1925, estadio: 'New York Stadium', serie: 'EFL Championship' },
  { codigo: 257, nome: 'Huddersfield Town', anoFundacao: 1908, estadio: 'John Smith\'s Stadium', serie: 'EFL Championship' },
  { codigo: 258, nome: 'Birmingham', anoFundacao: 1875, estadio: 'St. Andrew\'s', serie: 'EFL Championship' },
  { codigo: 259, nome: 'Bristol Rovers', anoFundacao: 1883, estadio: 'Memorial Stadium', serie: 'EFL League One' },
  { codigo: 260, nome: 'Wigan Athletic', anoFundacao: 1932, estadio: 'DW Stadium', serie: 'EFL League One' },
  { codigo: 261, nome: 'Oxford United', anoFundacao: 1893, estadio: 'Kassam Stadium', serie: 'EFL League One' },
  { codigo: 262, nome: 'Wycombe Wanderers', anoFundacao: 1887, estadio: 'Adams Park', serie: 'EFL League One' },
  { codigo: 263, nome: 'Ipswich Town', anoFundacao: 1878, estadio: 'Portman Road', serie: 'EFL League One' },
  { codigo: 264, nome: 'Cambridge United', anoFundacao: 1912, estadio: 'Abbey Stadium', serie: 'EFL League One' },
  { codigo: 265, nome: 'Morecambe', anoFundacao: 1920, estadio: 'Mazuma Stadium', serie: 'EFL League One' },
  { codigo: 266, nome: 'Lincoln City', anoFundacao: 1884, estadio: 'Sincil Bank', serie: 'EFL League One' },
  { codigo: 267, nome: 'Accrington Stanley', anoFundacao: 1968, estadio: 'Wham Stadium', serie: 'EFL League One' },
  { codigo: 268, nome: 'Fleetwood Town', anoFundacao: 1997, estadio: 'Highbury Stadium', serie: 'EFL League One' },
  { codigo: 269, nome: 'Shrewsbury Town', anoFundacao: 1886, estadio: 'New Meadow', serie: 'EFL League One' },
  { codigo: 270, nome: 'Doncaster Rovers', anoFundacao: 1879, estadio: 'Eco-Power Stadium', serie: 'EFL League One' },
  { codigo: 271, nome: 'Charlton Athletic', anoFundacao: 1905, estadio: 'The Valley', serie: 'EFL League One' },
  { codigo: 272, nome: 'Swindon Town', anoFundacao: 1879, estadio: 'County Ground', serie: 'EFL League One' },
  { codigo: 273, nome: 'Barrow', anoFundacao: 1901, estadio: 'Holker Street', serie: 'EFL League Two' },
  { codigo: 274, nome: 'Chesterfield', anoFundacao: 1867, estadio: 'Technique Stadium', serie: 'EFL League Two' },
  { codigo: 275, nome: 'Harrogate Town', anoFundacao: 1914, estadio: 'CNG Stadium', serie: 'EFL League Two' },
  { codigo: 276, nome: 'Bristol City', anoFundacao: 1894, estadio: 'Ashton Gate', serie: 'EFL Championship' },
  { codigo: 277, nome: 'Wolverhampton Wanderers', anoFundacao: 1877, estadio: 'Molineux Stadium', serie: 'EFL Championship' },
  { codigo: 278, nome: 'Manchester City', anoFundacao: 1880, estadio: 'Etihad Stadium', serie: 'Premier League' },
  { codigo: 279, nome: 'Manchester United', anoFundacao: 1878, estadio: 'Old Trafford', serie: 'Premier League' },
  { codigo: 280, nome: 'Arsenal', anoFundacao: 1886, estadio: 'Emirates Stadium', serie: 'Premier League' },
  { codigo: 281, nome: 'Liverpool', anoFundacao: 1892, estadio: 'Anfield', serie: 'Premier League' },
  { codigo: 282, nome: 'Tottenham Hotspur', anoFundacao: 1882, estadio: 'Tottenham Hotspur Stadium', serie: 'Premier League' },
  { codigo: 283, nome: 'Chelsea', anoFundacao: 1905, estadio: 'Stamford Bridge', serie: 'Premier League' },
  { codigo: 284, nome: 'Leicester City', anoFundacao: 1884, estadio: 'King Power Stadium', serie: 'Premier League' },
  { codigo: 285, nome: 'Aston Villa', anoFundacao: 1874, estadio: 'Villa Park', serie: 'Premier League' },
  { codigo: 286, nome: 'West Ham United', anoFundacao: 1895, estadio: 'London Stadium', serie: 'Premier League' },
  { codigo: 287, nome: 'Everton', anoFundacao: 1878, estadio: 'Goodison Park', serie: 'Premier League' },
  { codigo: 288, nome: 'Newcastle United', anoFundacao: 1892, estadio: 'St James\' Park', serie: 'Premier League' },
  { codigo: 289, nome: 'Burnley', anoFundacao: 1882, estadio: 'Turf Moor', serie: 'Premier League' },
  { codigo: 290, nome: 'Nottingham Forest', anoFundacao: 1865, estadio: 'City Ground', serie: 'Premier League' },
  { codigo: 291, nome: 'Fulham', anoFundacao: 1879, estadio: 'Craven Cottage', serie: 'Premier League' },
  { codigo: 292, nome: 'Brentford', anoFundacao: 1889, estadio: 'Brentford Community Stadium', serie: 'Premier League' },
  { codigo: 293, nome: 'Luton Town', anoFundacao: 1885, estadio: 'Kenilworth Road', serie: 'Premier League' },
  { codigo: 294, nome: 'Sheffield United', anoFundacao: 1889, estadio: 'Bramall Lane', serie: 'Premier League' },
  { codigo: 295, nome: 'Crystal Palace', anoFundacao: 1905, estadio: 'Selhurst Park', serie: 'Premier League' },
  { codigo: 296, nome: 'Bournemouth', anoFundacao: 1890, estadio: 'Vitality Stadium', serie: 'Premier League' },
  { codigo: 297, nome: 'Blackburn Rovers', anoFundacao: 1875, estadio: 'Ewood Park', serie: 'EFL Championship' },
  { codigo: 298, nome: 'Cardiff City', anoFundacao: 1899, estadio: 'Cardiff City Stadium', serie: 'EFL Championship' },
  { codigo: 299, nome: 'Huddersfield Town', anoFundacao: 1908, estadio: 'John Smith\'s Stadium', serie: 'EFL Championship' },
  { codigo: 300, nome: 'Luton Town', anoFundacao: 1885, estadio: 'Kenilworth Road', serie: 'EFL Championship' },
  { codigo: 301, nome: 'Coventry City', anoFundacao: 1883, estadio: 'Coventry Building Society Arena', serie: 'EFL Championship' },
  { codigo: 302, nome: 'Swansea City', anoFundacao: 1912, estadio: 'Swansea.com Stadium', serie: 'EFL Championship' },
  { codigo: 303, nome: 'Barnsley', anoFundacao: 1887, estadio: 'Oakwell', serie: 'EFL Championship' },
  { codigo: 304, nome: 'Middlesbrough', anoFundacao: 1876, estadio: 'Riverside Stadium', serie: 'EFL Championship' },
  { codigo: 305, nome: 'Nottingham Forest', anoFundacao: 1865, estadio: 'City Ground', serie: 'EFL Championship' },
  { codigo: 306, nome: 'Sheffield Wednesday', anoFundacao: 1867, estadio: 'Hillsborough Stadium', serie: 'EFL Championship' },
  { codigo: 307, nome: 'West Bromwich Albion', anoFundacao: 1878, estadio: 'The Hawthorns', serie: 'EFL Championship' },
  { codigo: 308, nome: 'Charlton Athletic', anoFundacao: 1905, estadio: 'The Valley', serie: 'EFL League One' },
  { codigo: 309, nome: 'Wigan Athletic', anoFundacao: 1932, estadio: 'DW Stadium', serie: 'EFL League One' },
  { codigo: 310, nome: 'Sunderland', anoFundacao: 1879, estadio: 'Stadium of Light', serie: 'EFL League One' },
  { codigo: 311, nome: 'Bradford City', anoFundacao: 1903, estadio: 'Valley Parade', serie: 'EFL League Two' },
  { codigo: 312, nome: 'Port Vale', anoFundacao: 1876, estadio: 'Vale Park', serie: 'EFL League Two' },
  { codigo: 313, nome: 'Southend United', anoFundacao: 1906, estadio: 'Roots Hall', serie: 'EFL League Two' },
  { codigo: 314, nome: 'Lincoln City', anoFundacao: 1884, estadio: 'Sincil Bank', serie: 'EFL League Two' },
  { codigo: 315, nome: 'Cambridge United', anoFundacao: 1912, estadio: 'Abbey Stadium', serie: 'EFL League Two' },
  { codigo: 316, nome: 'Colchester United', anoFundacao: 1937, estadio: 'JobServe Community Stadium', serie: 'EFL League Two' },
  { codigo: 317, nome: 'Hartlepool United', anoFundacao: 1908, estadio: 'Victoria Park', serie: 'EFL League Two' },
  { codigo: 318, nome: 'Scunthorpe United', anoFundacao: 1899, estadio: 'Glanford Park', serie: 'EFL League Two' },
  { codigo: 319, nome: 'Stevenage', anoFundacao: 1976, estadio: 'Lamex Stadium', serie: 'EFL League Two' },
  { codigo: 320, nome: 'Tranmere Rovers', anoFundacao: 1884, estadio: 'Prenton Park', serie: 'EFL League Two' },
  { codigo: 321, nome: 'Walsall', anoFundacao: 1888, estadio: 'Bescot Stadium', serie: 'EFL League Two' },
  { codigo: 322, nome: 'Gillingham', anoFundacao: 1893, estadio: 'Priestfield Stadium', serie: 'EFL League Two' },
  { codigo: 323, nome: 'Oldham Athletic', anoFundacao: 1895, estadio: 'Boundary Park', serie: 'EFL League Two' },
  { codigo: 324, nome: 'Newport County', anoFundacao: 1912, estadio: 'Rodney Parade', serie: 'EFL League Two' },
  { codigo: 325, nome: 'Rotherham United', anoFundacao: 1925, estadio: 'New York Stadium', serie: 'EFL Championship' },
  { codigo: 326, nome: 'Walsall', anoFundacao: 1888, estadio: 'Bescot Stadium', serie: 'EFL League Two' },
  { codigo: 327, nome: 'Leyton Orient', anoFundacao: 1881, estadio: 'Brisbane Road', serie: 'EFL League Two' },
  { codigo: 328, nome: 'Mansfield Town', anoFundacao: 1897, estadio: 'One Call Stadium', serie: 'EFL League Two' },
  { codigo: 329, nome: 'Northampton Town', anoFundacao: 1897, estadio: 'Sixfields Stadium', serie: 'EFL League Two' },
  { codigo: 330, nome: 'Harrogate Town', anoFundacao: 1914, estadio: 'CNG Stadium', serie: 'EFL League Two' },
  { codigo: 331, nome: 'Barrow', anoFundacao: 1901, estadio: 'Holker Street', serie: 'EFL League Two' },
  { codigo: 332, nome: 'Carlisle United', anoFundacao: 1904, estadio: 'Brunton Park', serie: 'EFL League Two' },
  { codigo: 333, nome: 'Fleetwood Town', anoFundacao: 1997, estadio: 'Highbury Stadium', serie: 'EFL League One' },
  { codigo: 334, nome: 'Bristol Rovers', anoFundacao: 1883, estadio: 'Memorial Stadium', serie: 'EFL League One' },
  { codigo: 335, nome: 'Oxford United', anoFundacao: 1893, estadio: 'Kassam Stadium', serie: 'EFL League One' },
  { codigo: 336, nome: 'Plymouth Argyle', anoFundacao: 1886, estadio: 'Home Park', serie: 'EFL League One' },
  { codigo: 337, nome: 'Accrington Stanley', anoFundacao: 1968, estadio: 'Wham Stadium', serie: 'EFL League One' },
  { codigo: 338, nome: 'Portsmouth', anoFundacao: 1898, estadio: 'Fratton Park', serie: 'EFL League One' },
  { codigo: 339, nome: 'Doncaster Rovers', anoFundacao: 1879, estadio: 'Eco-Power Stadium', serie: 'EFL League One' },
  { codigo: 340, nome: 'Lincoln City', anoFundacao: 1884, estadio: 'Sincil Bank', serie: 'EFL League One' },
  { codigo: 341, nome: 'Gillingham', anoFundacao: 1893, estadio: 'Priestfield Stadium', serie: 'EFL League One' },
  { codigo: 342, nome: 'Chesterfield', anoFundacao: 1867, estadio: 'Technique Stadium', serie: 'EFL League Two' },
  { codigo: 343, nome: 'York City', anoFundacao: 1922, estadio: 'LNER Community Stadium', serie: 'EFL League Two' },
  { codigo: 344, nome: 'Aldershot Town', anoFundacao: 1992, estadio: 'The Electrical Services Stadium', serie: 'EFL League Two' },
  { codigo: 345, nome: 'Solihull Moors', anoFundacao: 2007, estadio: 'Damson Park', serie: 'EFL League Two' },
  { codigo: 346, nome: 'Dagenham & Redbridge', anoFundacao: 1992, estadio: 'Victoria Road', serie: 'EFL League Two' },
  { codigo: 347, nome: 'Eastleigh', anoFundacao: 1946, estadio: 'Silverlake Stadium', serie: 'National League' },
  { codigo: 348, nome: 'Woking', anoFundacao: 1889, estadio: 'Kingfield Stadium', serie: 'National League' },
  { codigo: 349, nome: 'Bromley', anoFundacao: 1892, estadio: 'Hayes Lane', serie: 'National League' },
  { codigo: 350, nome: 'Wealdstone', anoFundacao: 1899, estadio: 'The Grosvenor Vale', serie: 'National League' },
  { codigo: 351, nome: 'Maidenhead United', anoFundacao: 1870, estadio: 'York Road', serie: 'National League' },
  { codigo: 352, nome: 'Notts County', anoFundacao: 1862, estadio: 'Meadow Lane', serie: 'National League' },
  { codigo: 353, nome: 'Chester', anoFundacao: 2010, estadio: 'Deva Stadium', serie: 'National League' },
  { codigo: 354, nome: 'Altrincham', anoFundacao: 1891, estadio: 'Moss Lane', serie: 'National League' },
  { codigo: 355, nome: 'Stockport County', anoFundacao: 1883, estadio: 'Edgeley Park', serie: 'National League' },
  { codigo: 356, nome: 'Darlington', anoFundacao: 1883, estadio: 'Blackwell Meadows', serie: 'National League' },
  { codigo: 357, nome: 'Solihull Moors', anoFundacao: 2007, estadio: 'Damson Park', serie: 'National League' },
  { codigo: 358, nome: 'Braintree Town', anoFundacao: 1898, estadio: 'Cressing Road', serie: 'National League' },
  { codigo: 359, nome: 'AFC Fylde', anoFundacao: 1886, estadio: 'Mill Farm', serie: 'National League' },
  { codigo: 360, nome: 'Boreham Wood', anoFundacao: 1948, estadio: 'Meadow Park', serie: 'National League' },
  { codigo: 361, nome: 'Torquay United', anoFundacao: 1899, estadio: 'Plainmoor', serie: 'National League' },
  { codigo: 362, nome: 'Barnet', anoFundacao: 1888, estadio: 'The Hive London', serie: 'National League' },
  { codigo: 363, nome: 'Eastbourne Borough', anoFundacao: 1920, estadio: 'Priory Lane', serie: 'National League' },
  { codigo: 364, nome: 'Welling United', anoFundacao: 1963, estadio: 'Park View Road', serie: 'National League' },
  { codigo: 365, nome: 'York City', anoFundacao: 1922, estadio: 'LNER Community Stadium', serie: 'National League' },
  { codigo: 366, nome: 'Kidderminster Harriers', anoFundacao: 1881, estadio: 'Aggborough', serie: 'National League' },
  { codigo: 367, nome: 'Gloucester City', anoFundacao: 1883, estadio: 'Whaddon Road', serie: 'National League' },
  { codigo: 368, nome: 'Dover Athletic', anoFundacao: 1983, estadio: 'Crabble Athletic Ground', serie: 'National League' },
  { codigo: 369, nome: 'Farsley Celtic', anoFundacao: 1908, estadio: 'The Citadel', serie: 'National League' },
  { codigo: 370, nome: 'Kettering Town', anoFundacao: 1872, estadio: 'Latimer Park', serie: 'National League' },
  { codigo: 371, nome: 'Bishop’s Stortford', anoFundacao: 1874, estadio: 'Woodside Park', serie: 'National League' },
  { codigo: 372, nome: 'Brackley Town', anoFundacao: 1890, estadio: 'St. James Park', serie: 'National League' },
  { codigo: 373, nome: 'Chorley', anoFundacao: 1883, estadio: 'Victory Park', serie: 'National League' },
  { codigo: 374, nome: 'Oxford City', anoFundacao: 1882, estadio: 'Marsh Lane', serie: 'National League' },
  { codigo: 375, nome: 'Wrexham', anoFundacao: 1864, estadio: 'Racecourse Ground', serie: 'National League' },
  { codigo: 376, nome: 'Alfreton Town', anoFundacao: 1957, estadio: 'North Street', serie: 'National League' },
  { codigo: 377, nome: 'Telford United', anoFundacao: 2004, estadio: 'New Bucks Head', serie: 'National League' },
  { codigo: 378, nome: 'Gainsborough Trinity', anoFundacao: 1873, estadio: 'The Northolme', serie: 'National League' },
  { codigo: 379, nome: 'Southport', anoFundacao: 1881, estadio: 'Haig Avenue', serie: 'National League' },
  { codigo: 380, nome: 'Maidstone United', anoFundacao: 1993, estadio: 'Gallagher Stadium', serie: 'National League' },
  { codigo: 381, nome: 'Dartford', anoFundacao: 1884, estadio: 'Princes Park', serie: 'National League' },
  { codigo: 382, nome: 'Bromley', anoFundacao: 1892, estadio: 'Hayes Lane', serie: 'National League' },
  { codigo: 383, nome: 'Chesham United', anoFundacao: 1917, estadio: 'The Meadow', serie: 'National League' },
  { codigo: 384, nome: 'St Albans City', anoFundacao: 1908, estadio: 'Clarence Park', serie: 'National League' },
  { codigo: 385, nome: 'Welling United', anoFundacao: 1963, estadio: 'Park View Road', serie: 'National League' },
  { codigo: 386, nome: 'Gateshead', anoFundacao: 1889, estadio: 'Gateshead International Stadium', serie: 'National League' },
  { codigo: 387, nome: 'Halifax Town', anoFundacao: 2008, estadio: 'The Shay', serie: 'National League' },
  { codigo: 388, nome: 'Harrogate Town', anoFundacao: 1914, estadio: 'CNG Stadium', serie: 'National League' },
  { codigo: 389, nome: 'Darlington', anoFundacao: 1883, estadio: 'Blackwell Meadows', serie: 'National League' },
  { codigo: 390, nome: 'Dover Athletic', anoFundacao: 1983, estadio: 'Crabble Athletic Ground', serie: 'National League' },
  { codigo: 391, nome: 'Braintree Town', anoFundacao: 1898, estadio: 'Cressing Road', serie: 'National League' },
  { codigo: 392, nome: 'Oxford City', anoFundacao: 1882, estadio: 'Marsh Lane', serie: 'National League' },
  { codigo: 393, nome: 'Boston United', anoFundacao: 1933, estadio: 'York Street', serie: 'National League' },
  { codigo: 394, nome: 'Curzon Ashton', anoFundacao: 1963, estadio: 'Tameside Stadium', serie: 'National League' },
  { codigo: 395, nome: 'Farsley Celtic', anoFundacao: 1908, estadio: 'The Citadel', serie: 'National League' },
  { codigo: 396, nome: 'Bishop’s Stortford', anoFundacao: 1874, estadio: 'Woodside Park', serie: 'National League' },
  { codigo: 397, nome: 'Chippenham Town', anoFundacao: 2001, estadio: 'Hardenhuish Park', serie: 'National League' },
  { codigo: 398, nome: 'Woking', anoFundacao: 1889, estadio: 'Kingfield Stadium', serie: 'National League' },
  { codigo: 399, nome: 'Eastleigh', anoFundacao: 1946, estadio: 'Silverlake Stadium', serie: 'National League' },
  { codigo: 400, nome: 'Hungerford Town', anoFundacao: 1886, estadio: 'Bulpit Lane', serie: 'National League' },
  { codigo: 401, nome: 'Maidstone United', anoFundacao: 1993, estadio: 'Gallagher Stadium', serie: 'National League' },
  { codigo: 402, nome: 'Welling United', anoFundacao: 1963, estadio: 'Park View Road', serie: 'National League' },
  { codigo: 403, nome: 'Darlington', anoFundacao: 1883, estadio: 'Blackwell Meadows', serie: 'National League' },
  { codigo: 404, nome: 'Bromley', anoFundacao: 1892, estadio: 'Hayes Lane', serie: 'National League' },
  { codigo: 405, nome: 'Barnet', anoFundacao: 1888, estadio: 'The Hive London', serie: 'National League' },
  { codigo: 406, nome: 'Kettering Town', anoFundacao: 1872, estadio: 'Latimer Park', serie: 'National League' },
  { codigo: 407, nome: 'Wrexham', anoFundacao: 1864, estadio: 'Racecourse Ground', serie: 'National League' },
  { codigo: 408, nome: 'Stockport County', anoFundacao: 1883, estadio: 'Edgeley Park', serie: 'National League' },
  { codigo: 409, nome: 'Southport', anoFundacao: 1881, estadio: 'Haig Avenue', serie: 'National League' },
  { codigo: 410, nome: 'Boston United', anoFundacao: 1933, estadio: 'York Street', serie: 'National League' },
  { codigo: 411, nome: 'Woking', anoFundacao: 1889, estadio: 'Kingfield Stadium', serie: 'National League' },
  { codigo: 412, nome: 'Chester', anoFundacao: 2010, estadio: 'Deva Stadium', serie: 'National League' },
  { codigo: 413, nome: 'Bromley', anoFundacao: 1892, estadio: 'Hayes Lane', serie: 'National League' },
  { codigo: 414, nome: 'Southport', anoFundacao: 1881, estadio: 'Haig Avenue', serie: 'National League' },
  { codigo: 415, nome: 'Altrincham', anoFundacao: 1891, estadio: 'Moss Lane', serie: 'National League' },
  { codigo: 416, nome: 'Gateshead', anoFundacao: 1889, estadio: 'Gateshead International Stadium', serie: 'National League' },
  { codigo: 417, nome: 'Harrogate Town', anoFundacao: 1914, estadio: 'CNG Stadium', serie: 'National League' },
  { codigo: 418, nome: 'Eastleigh', anoFundacao: 1946, estadio: 'Silverlake Stadium', serie: 'National League' },
  { codigo: 419, nome: 'Darlington', anoFundacao: 1883, estadio: 'Blackwell Meadows', serie: 'National League' },
  { codigo: 420, nome: 'Chesterfield', anoFundacao: 1867, estadio: 'Technique Stadium', serie: 'National League' }

// Outros times...
];

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss']
})
export class TableComponent implements AfterViewInit {
  displayedColumns: string[] = ['codigo', 'nome', 'anoFundacao', 'estadio', 'serie'];
  dataSource = new MatTableDataSource(TIMES_DATA);

  @ViewChild(MatSort) sort!: MatSort;
  @ViewChild(MatPaginator) paginator!: MatPaginator;

  ngAfterViewInit(): void {
    // Vinculando o MatSort e MatPaginator ao dataSource
    this.dataSource.sort = this.sort;
    this.dataSource.paginator = this.paginator;
  }

  // Método para aplicar o filtro
  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();

    // Redefine a paginação após filtrar
    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }
}
